### ISSUE TITLE
changing weekly meeting time?

### ISSUE THREAD

**Issue by j-chou** [kochkov92/Tictactoe#1]
hey guys, is it possible to reschedule the weekly meeting time to say 1pm? 11am is difficult for me because my gf needs to use the car at that time to go to the gym, so my available time is constrained by when she is done. also, if it was at 1pm, we could have lunch before the meeting. what do you guys think?

**Comment by kochkov92** [comment]
Hey Jed,

I’m generally quite flexible on Sundays, so there are no hard constrains for me, but in general I would prefer to work a little
bit earlier at least on some days, to save the day time for other activities. I see several options that can probably fit us all. We can
cycle the location where we meet every other time, in which case sometimes we can start at 1 at my or Mihns’ place and at 11ish
 at yours place.

Dima

**Comment by jdove2** [comment]
I'm available most of Sundays aswell.  Minh tends to invite people over on
Sundays for boardgames in the evening, but either than that I am free to
shift times/locations around.

Jason

**Comment by j-chou** [comment]
Great, so 1pm this Sunday works for Dima as well. So let's do that.

**Comment by jdove2** [comment]
Where are we meeting this week?  I forgot we were supposed to meet at
Dima's last week and when I called him he didnt answer the phone so I
thought he had just forgot to come to my place.  I made cake today if you
wanted to come here :)

Jason

**Comment by jdove2** [comment]
I have a meeting tomorrow 10/18 at 3pm.  Is it possible to start out
meeting earlier?  If you have one of us pick you up is it ok to start at
like 11 Jed?

Jason

**Comment by j-chou** [comment]
Hey, yeah for sure. My gf will drop me off, but I might need a ride back.

Jed
